documents:
  subset_size: 10
  source: data/compendium/compendium_english.json
  target: data/compendium/10/compendium_train.jsonl
knowledge_base:
  dataset: catechism
  source: data/compendium/catechism_english.jsonl
  target: data/compendium/10/catechism_kb.duckdb
  use_subset: True
embedder:
  model: jinaai/jina-embeddings-v3
  task: text-matching
  query_task: retrieval.query
index:
  batch_size: 25
  type: sparse
  name: data/compendium/10/compendium_sparse
  temp_file: data/compendium/paragraphs.jsonl
