documents:
  subset_size: 10000
  target: data/01_dense/kilt_fever_train.jsonl
  dataset: fever
knowledge_base:
  source: data/wikipedia_kilt.duckdb
  target: data/01_dense/kilt_wiki.duckdb
  use_subset: True
embedder:
  model: jinaai/jina-embeddings-v3
  task: text-matching
  query_task: retrieval.query
index:
  dim: 1024
  batch_size: 25
  dense:
    path: data/01_dense/kilt_wiki.index
