documents:
  subset_size: 10
  target: data/10/kilt_fever_train.jsonl
knowledge_base:
  wiki_source: data/wikipedia_kilt.duckdb
  target: data/10/kilt_wiki.duckdb
  use_subset: True
embedder:
  model: jinaai/jina-embeddings-v3
  task: text-matching
  query_task: retrieval.query
index:
  # type: sparse
  # name: data/10/wiki_sparse
  # temp_file: data/10/paragraphs.jsonl

  type: dense
  name: data/10/kilt_wiki.index
  dim: 1024
  batch_size: 25
retriever:
  k: 5
  strategy: dense
generator:
  model: google/gemma-3-12b-it
  base_url: http://trinity.zhaw.ch:8651/v1
  temperature: 0.7
  max_tokens: 512
  system_prompt: >
    You are a master fact checker.
    From given passages and a claim you can say whether the claim is SUPPORTS, REFUTES.
    If the passages do not provide a clear answer you need to say "NOT ENOUGH INFO".
    Only answer with one of the given labels: SUPPORTS, REFUTES, NOT ENOUGH INFO.