
documents:
  target: data/compendium/all/compendium_train.jsonl
knowledge_base:
  dataset: catechism
  target: data/compendium/all/catechism_kb.duckdb
embedder:
  model: jinaai/jina-embeddings-v3
  query_task: retrieval.query
retriever:
  k: 5
generator:
  model: google/gemma-3-12b-it
  base_url: http://sanjose.zhaw.ch:8651/v1
  temperature: 0.7
  max_tokens: 512
  system_prompt: >
    Du bist ein theologischer Experte auf dem Gebiet der römisch-christlichen Kirche.
    Dir wird eine Frage gestellt, die du anhand der gegebenen Textstellen beantworten sollst.
    Sei sehr präzise und füge nichts hinzu, was nicht in den gegebenen Textstellen enthalten ist.
judge:
  model: google/gemma-3-12b-it
  base_url: http://sanjose.zhaw.ch:8651/v1
  temperature: 0.7
  max_tokens: 512
  system_prompt: >
    Dir werden eine Frage, die abgerufenen Textstellen, die Referenzantwort und eine generierte Antwort gegeben.
    Du sollst beurteilen, ob die generierte Antwort der Referenzantwort ähnlich ist.

    Die Antworten sind ähnlich, wenn sie die gleiche Kernaussage haben.

    Antworte ausschliesslich mit True oder False.