
embedder:
  model: jinaai/jina-embeddings-v3
  query_task: retrieval.query
retriever:
  k: 5
generator:
  model: google/gemma-3-12b-it
  base_url: http://sanjose.zhaw.ch:8651/v1
  temperature: 0.7
  max_tokens: 512
  system_prompt: >
    You are an expert in all kinds of questions.
    Answer the users question given a list of retrieved paragraphs.
    Only answer using the retrieved paragraphs.
    If you do not know the answer say: I DO NOT KNOW.
judge:
  model: google/gemma-3-12b-it
  base_url: http://sanjose.zhaw.ch:8651/v1
  temperature: 0.7
  max_tokens: 512
  system_prompt: >
    You are given a question, the retrieved paragraphs, the reference answer and a generated answer.
    You need to judge whether the generated answer is similar the reference answer.

    The answers are similar if they have the same core idea.

    Answer with True or False only.